#Tridents enchanted with loyalty will return when thrown into the void.
#Default Value: true
return_trident_from_void = true
#Tridents enchanted with loyalty bring drops and xp from the entity they have killed to the player (both melee and ranged combat).
#Default Value: true
loyalty_captures_drops = true
#Tridents can be repaired in an anvil using prismarine shards.
#Default Value: true
repair_tridents = true
#Tridents will be picked up in the slot they were thrown from.
#Default Value: true
return_trident_to_slot = true
