#Chargers configs
[chargers]

	[chargers.tier_1]
		#The amount of energy the charger can hold
		# Default: 25000
		# Range: 0 ~ 9223372036854775807
		storage = 25000
		#The amount of energy/tick that can be inserted
		# Default: 500
		# Range: 0 ~ 9223372036854775807
		max_input = 500
		#The amount of energy/tick that can be extracted
		#This is the max speed items would be charged at, actual speed could be slower depending on item
		# Default: 500
		# Range: 0 ~ 9223372036854775807
		max_output = 500

	[chargers.tier_2]
		#The amount of energy the charger can hold
		# Default: 500000
		# Range: 0 ~ 9223372036854775807
		storage = 500000
		#The amount of energy/tick that can be inserted
		# Default: 10000
		# Range: 0 ~ 9223372036854775807
		max_input = 10000
		#The amount of energy/tick that can be extracted
		#This is the max speed items would be charged at, actual speed could be slower depending on item
		# Default: 10000
		# Range: 0 ~ 9223372036854775807
		max_output = 10000

	[chargers.tier_3]
		#The amount of energy the charger can hold
		# Default: 1000000
		# Range: 0 ~ 9223372036854775807
		storage = 1000000
		#The amount of energy/tick that can be inserted
		# Default: 25000
		# Range: 0 ~ 9223372036854775807
		max_input = 25000
		#The amount of energy/tick that can be extracted
		#This is the max speed items would be charged at, actual speed could be slower depending on item
		# Default: 25000
		# Range: 0 ~ 9223372036854775807
		max_output = 25000

	[chargers.tier_4]
		#The amount of energy the charger can hold
		# Default: 25000000
		# Range: 0 ~ 9223372036854775807
		storage = 25000000
		#The amount of energy/tick that can be inserted
		# Default: 625000
		# Range: 0 ~ 9223372036854775807
		max_input = 625000
		#The amount of energy/tick that can be extracted
		#This is the max speed items would be charged at, actual speed could be slower depending on item
		# Default: 625000
		# Range: 0 ~ 9223372036854775807
		max_output = 625000

	[chargers.wireless]
		#The amount of energy the wireless charger can hold
		# Default: 200000
		# Range: 0 ~ 9223372036854775807
		storage = 200000
		#The amount of energy/tick that can be inserted
		# Default: 4000
		# Range: 0 ~ 9223372036854775807
		max_input = 4000
		#The amount of energy/tick that can be extracted
		#This is the max speed items would be charged at, actual speed could be slower depending on item
		# Default: 4000
		# Range: 0 ~ 9223372036854775807
		max_output = 4000
		#The range from the charger that item will be charged
		# Default: 24
		# Range: 0 ~ 128
		range = 24

#Compat configs
[compat]
	#If the wireless charger should charge curios items
	curios_compat = true
